# utils/play_next.py
import discord
import asyncio
from googleapiclient.discovery import build
import time
from bot_config import YT_TOKEN
from utils.ytdl_source import YTDLSource
from utils.queues import queues
from utils.music_controls import MusicControlView 

async def play_next(guild: discord.Guild, channel: discord.TextChannel, requester_id: int):
    voice_client = guild.voice_client

    # 음성 클라이언트가 없거나 연결되지 않은 경우
    if not voice_client or not voice_client.is_connected():
        await channel.send("음성 채널에 연결되어 있지 않습니다. 재생을 중단합니다.")
        if guild.id in queues:
            queues[guild.id].clear()
        return

    # 대기열에 곡이 없는 경우
    if guild.id not in queues or not queues[guild.id]:
        if voice_client.is_connected():
            await voice_client.disconnect()
            await channel.send("대기열이 비어 있어 음성 채널에서 나갑니다.")
        return

    # 다음 곡 재생
    next_song = queues[guild.id].popleft()
    try:
        # 곡 정보 가져오기
        player = await YTDLSource.from_url(next_song, loop=asyncio.get_event_loop())
        if isinstance(player, list):
            player = player[0]
        player.start_time = time.time()

        # 재생 시작
        voice_client.play(player, after=lambda e: asyncio.run_coroutine_threadsafe(
            play_next(guild, channel, requester_id), voice_client.loop))
        
        # 임베드 생성 및 전송
        embed = await create_song_embed(player, guild, requester_id, voice_client)
        
        # 버튼 뷰 생성
        view = MusicControlView(guild.id)
        
        # 임베드와 버튼을 함께 전송
        await channel.send(embed=embed, view=view)
    except Exception as e:
        await channel.send(f"재생 중 오류 발생: {str(e)}")

async def create_song_embed(player, guild, requester_id, voice_client):
    # YouTube API로 채널 정보 가져오기
    youtube = build('youtube', 'v3', developerKey=YT_TOKEN)
    channel_id = player.data.get('channel_id')
    if not channel_id:
        raise ValueError("채널 ID를 찾을 수 없습니다.")

    # 채널 정보 요청
    channel_response = youtube.channels().list(part="snippet", id=channel_id).execute()
    uploader_thumbnail = None
    if 'items' in channel_response and channel_response['items']:
        uploader_thumbnail = channel_response['items'][0]['snippet']['thumbnails']['default']['url']

    # 임베드 생성
    song_url = f"https://www.youtube.com/watch?v={player.data.get('id')}"
    embed = discord.Embed(title=player.title, url=song_url, color=0x0061ff)

    # 업로더 정보 설정
    uploader_name = player.data.get('uploader', 'Unknown Uploader')
    is_auto_generated = 'Auto-generated by YouTube' in player.data.get('description', '')
    channel_url = f"https://www.youtube.com/channel/{channel_id}"

    if is_auto_generated:
        name_with_check = f"{uploader_name.split(' - Topic')[0]}☑️" if is_auto_generated else uploader_name
    else:
        name_with_check = uploader_name

    embed.set_author(name=name_with_check, url=channel_url, 
                    icon_url=uploader_thumbnail or player.data.get('thumbnail'))

    # 썸네일 설정
    if player.thumbnail:
        embed.set_thumbnail(url=player.thumbnail)

    # 재생 시간 설정
    duration_seconds = player.data.get('duration', 0)
    embed.add_field(name="Duration", value=format_duration(duration_seconds), inline=True)
    
    # 요청자 정보 설정
    requester = guild.get_member(requester_id)
    requester_mention = requester.mention if requester else "알 수 없음"
    embed.add_field(name="Request", value=requester_mention, inline=True)

    if is_auto_generated:
        embed.add_field(name="Artist", value=uploader_name.split(" - Topic")[0], inline=True)

    # 푸터 설정
    voice_channel_name = voice_client.channel.name if voice_client.channel else "Unknown Channel"
    embed.set_footer(text=f"{voice_channel_name} / {guild.me.name}")

    return embed

def format_duration(seconds):
    hours, remainder = divmod(int(seconds), 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}" if hours else f"{minutes:02d}:{seconds:02d}"